CREATE TABLE `news`
(
`id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`title` VARCHAR(255) NOT NULL,
`content` TEXT NOT NULL,
`category` INT(1) NOT NULL,
`datetime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
;